name: build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.gitattributes'
      - '**/*.gitignore'
      - '**/*.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  

jobs:
  build:
    name: build
    runs-on: [ ubuntu-latest ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
          show-progress: true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        
      - name: Build 
        run: dotnet build -c Release
        
      - name: Tests 
        run: dotnet test -c Release --no-build